### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by MDHD-NoobCoder** [ZYunH/zmail#14]
`ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:749)`

How to deal with it?

**Comment by ZYunH** [comment]
Pls give me your mail server address ,such as @163.com, so i could locate the error.

**Comment by MDHD-NoobCoder** [comment]
@qq.com

**Comment by DiamondI** [comment]
**Same issue**

**Comment by ZYunH** [comment]
The problem has already solved in version 0.0.7, just reinstall it.

**Comment by MDHD-NoobCoder** [comment]
In pypi, version is still 0.0.6 .

**Comment by ZYunH** [comment]
OK,now is 0.0.7,thank you for feedback.

**Comment by MDHD-NoobCoder** [comment]
It works now. Thank you for bug fixing.

**Comment by DiamondI** [comment]
The error still exists after upgrade to 0.0.7 version. I guess I did something wrong with qq mail since the @126.com works well. Would you mind showing a specific example on how to use zmail with qq mail (or any other server address like this with extra confirmation needed?)

**Comment by MDHD-NoobCoder** [comment]
qqmail need open pop3 in settings->account. And remember to use pop3 password but not your QQ password.

**Comment by ZYunH** [comment]
@MDHD-NoobCoder , you can see README.md -> Supported mail serve.

**Comment by DiamondI** [comment]
I already opened the pop3 service and generated an authorization code. However, it still didn't work. I have generated another authorization code and tried another time just now, still couldn't work.

**Comment by ZYunH** [comment]
Could you give me the detailed info pls?@DiamondI

**Comment by DiamondI** [comment]
I don't want use qq mail anymore since I have already send many messages to get the so-called authorization code. And finally I found that I can't connect to the qq mail in my email client with the authorization code. I'd like to use other email account instead. Anyway, zmail is nice and it does well with my gmail. Thank you for creating this amazing tool !

**Comment by ZYunH** [comment]
Thank you~ @DiamondI
